name: Build Aseprite

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Download Skia
        shell: bash
        run: |
          curl -L -o skia.zip https://github.com/aseprite/skia/releases/download/m124-08a5439a6b/Skia-Windows-Release-x64.zip
          7z x skia.zip -oskia

      - name: Build Aseprite
        shell: bash
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo \
                -DLAF_BACKEND=skia \
                -DSKIA_DIR=${{ github.workspace }}/skia \
                -DSKIA_LIBRARY_DIR=${{ github.workspace }}/skia/out/Release-x64 \
                -DSKIA_LIBRARY=${{ github.workspace }}/skia/out/Release-x64/skia.lib \
                -DENABLE_WEBSOCKET=OFF \
                -G Ninja ..
          ninja aseprite

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Aseprite-Windows
          path: build/bin/
