name: Build Aseprite

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Ninja
        run: choco install ninja

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Download Skia
        shell: cmd
        run: |
          curl -L -o skia.zip https://github.com/aseprite/skia/releases/download/m124-08a5439a6b/Skia-Windows-Release-x64.zip
          7z x skia.zip -oskia

      - name: Build Aseprite
        shell: cmd
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DLAF_BACKEND=skia -DSKIA_DIR="%GITHUB_WORKSPACE%\skia" -DSKIA_LIBRARY_DIR="%GITHUB_WORKSPACE%\skia\out\Release-x64" -DSKIA_LIBRARY="%GITHUB_WORKSPACE%\skia\out\Release-x64\skia.lib" -DENABLE_UPDATER=OFF -DENABLE_WEBSOCKET=OFF -G Ninja ..
          ninja aseprite

      - name: Copy Missing DLLs
        shell: cmd
        run: |
          if exist "C:\Program Files\OpenSSL\bin\libcrypto-3-x64.dll" copy /Y "C:\Program Files\OpenSSL\bin\libcrypto-3-x64.dll" "build\bin\"
          if exist "C:\Program Files\OpenSSL\bin\libssl-3-x64.dll" copy /Y "C:\Program Files\OpenSSL\bin\libssl-3-x64.dll" "build\bin\"
          if exist "C:\Program Files\Git\mingw64\bin\libcrypto-3-x64.dll" copy /Y "C:\Program Files\Git\mingw64\bin\libcrypto-3-x64.dll" "build\bin\"
          if exist "C:\Program Files\Git\mingw64\bin\libssl-3-x64.dll" copy /Y "C:\Program Files\Git\mingw64\bin\libssl-3-x64.dll" "build\bin\"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Aseprite-Windows
          path: build/bin/
